---
apiVersion: v1
kind: Secret
metadata:
  name: cs-secrets
  namespace: myns
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=      # 'password' in base64
  SUDO_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cs-cm
  namespace: myns
  labels:
    app: cs
data:
  TZ: "Asia/Singapore"
  DEFAULT_WORKSPACE: "/config/workspace"
  PROXY_DOMAIN: "code-146-190-193-151.nip.io"