---
apiVersion: v1
kind: Secret
metadata:
  name: bgg-secret
  labels:
    app: bgg
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-cm
  labels:
    app: bgg
data:
    BGG_DB_USER: root
    BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local
    mysql.cf: |
      # this belongs to mysql.cf
      # not sure tbh
--- 
apiVersion: v1 
kind: Pod 
metadata:
  name: fakeapi-po 
  namespace: myns
  labels:
    app: fakeapi 
spec:
  volumes:
  - name: secret-vol
    secret:
      secretName: bgg-secret
  - name: config-vol
    configMap:
      name: bgg-cm
  # - name: data-vol
  #   emptyDir: {} # similar to volumeMount, shared within pod
    # hostPath:
    #   path: /opt/tmp
    #   type: DirectoryOrCreate #dangerous if you don't clean up the file as its shared by the container, similar to bindMount
  containers:
  # - name: filesync-containers 
  #   image: chukmunnlee/fake-api:v1
  #   imagePullPolicy: IfNotPresent
  #   volumeMounts:
  #   - name: data-vol
  #     mountPath: /pics
  #   resources: {}
  - name: fakeapi-containers 
    image: chukmunnlee/fake-api:v1
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: secret-vol
      mountPath: /opt/secrets
      readOnly: true
    - name: config-vol
      mountPath: /opt/config
    ports:
    - name: fakeapi-port 
      containerPort: 3000
    resources: {}