apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- dov-hpa.yaml

namespace: dev-ns

namePrefix: dev-
nameSuffix: -dev

labels:
- pairs:
    env: dev

replicas:
- name: dov-deploy
  count: 1

images:
- name: chukmunnlee/dov-bear:v5
  newTag: v1-medium

configMapGenerator: # using this will auto build the configmap as part of the kustomization
- name: dov-cm
  namespace: dov
  behavior: create # create, merge
  literals: 
  - INSTANCE_NAME="dev_env"

# demo of json patching
patches:
- path: remove-ingress.yaml
- path: add-resources.yaml # source of changes
  target: # target for changes
    group: apps
    version: v1
    kind: Deployment
    name: dov-deploy
    namespace: dov

replacements:
- source:
    kind: Service
    name: dov-svc
    namespace: dov
    fieldPath: metadata.name
  targets: # since its array, can apply 1 source to multiple targets
  - select:
      kind: Deployment
      name: dov-deploy
    fieldPaths:
    - spec.template.spec.containers.[name=dov-containers].env.[name=INSTANCE_HASH].value