---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
  labels:
    app: bgg
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bgg
      name: bggapp-po
  # image update strategy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  template:
    metadata:
      name: bggapp-po
      labels:
        app: bgg
        name: bggapp-po
    spec:
      containers:
      - name: bggapp-container
        image: stackupiss/bgg-backend:v2
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: bgg-cm
        - secretRef:
            name: bgg-secret
        ports:
        - name: bggapp-port
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz  
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    app: bgg
spec:
  # ClusterIP - svc is available inside the cluster only
  type: ClusterIP
  selector:
    #no need matchLabels or matchExpressions
    app: bgg
    name: bggapp-po
  ports:
  - name: bggapp-port
    port: 80
    targetPort: bggapp-port # this is a ref to a containerPort