---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
  labels:
    app: bgg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgg
      name: bggdb-po
  template:
    metadata:
      name: bggdb-po
      labels:
        app: bgg
        name: bggdb-po
    spec:
      containers:
      - name: bggdb-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: bggdb-port
          containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bgg
spec: 
  # clusterip - svc is available inside the cluster only
  type: ClusterIP
  selector:
    #no need matchLabels or matchExpressions
    app: bgg
    name: bggdb-po
  ports:
  - name: bggdb-port
    # same as above, but if diff can just reference portName bggdb-port
    port: 3306 

# Server:		10.109.0.10
# Address:	10.109.0.10#53

# Name:	bggdb-svc.bggns.svc.cluster.local
# Address: 10.109.26.133