---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: minio
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=      # 'password' in base64
  SUDO_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cm
  namespace: minio
  labels:
    app: minio
data:
  MINIO_ROOT_USER: "user"
  MINIO_ROOT_PASSWORD: "password"
  MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
  MINIO_DISTRIBUTED_NODES: "minio-deploy-{0...2}.minio-hsvc.minio.svc.cluster.local/data"
  MINIO_API_PORT_NUMBER: "9000"
  MINIO_CONSOLE_PORT_NUMBER: "9090"